@baseUrl = http://localhost:3000
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3Mzk5NDEzNzAsImV4cCI6MTc0MDAyNzc3MH0.o2zdF5Z1vLdOe9HnxNqOUOSnuz_LbYHS4PAdz_1_9hY

### Get JWT Token
GET {{baseUrl}}/auth/token

### Get All Gadgets
GET {{baseUrl}}/gadgets
Authorization: Bearer {{authToken}}

### Create New Gadget
POST {{baseUrl}}/gadgets
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "description": "A lipstick that is mini rocket launcher"
}


### Update Gadget Description
PATCH {{baseUrl}}/gadgets/93f712bb-e166-4467-b0e3-d6baa831fa4b
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "description": "Updated: A high-tech pen with enhanced electromagnetic pulse capability."
}

### Update Gadget Status
PATCH {{baseUrl}}/gadgets/93f712bb-e166-4467-b0e3-d6baa831fa4b
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "status": "DEPLOYED"
}

### Update Both Description and Status
PATCH {{baseUrl}}/gadgets/93f712bb-e166-4467-b0e3-d6baa831fa4b
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "description": "Updated description",
  "status": "DEPLOYED"
}

### Decommission Gadget
DELETE {{baseUrl}}/gadgets/93f712bb-e166-4467-b0e3-d6baa831fa4b
Authorization: Bearer {{authToken}}


### Request Self-Destruct Code
POST {{baseUrl}}/gadgets/8fc21a40-717f-4956-bad4-4e725c3c692d/self-destruct
Authorization: Bearer {{authToken}}

### Confirm Self-Destruct
POST {{baseUrl}}/gadgets/8fc21a40-717f-4956-bad4-4e725c3c692d/self-destruct/confirm
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "confirmationCode": "L2KDZS"
}